config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  resources :cases, only: [:index, :create, :new, :show]
  resources :users, only: [:create, :new, :show]
  resource :report, only: [:show]

  root 'root#index'
end

app/models/admin.rb
class Admin
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  index({ email: 1 }, { unique: true })

  validates :email, uniqueness: true

  def will_save_change_to_email?
  end
end

app/models/case.rb
class Case
  include Mongoid::Document

  def self.report
    Case.collection.aggregate([
      {
        '$sort': { date: -1 }
      },
      {
        '$project': {
          day: {
            '$dateToString': { format: '%Y-%m-%d', date: '$date' }
          },
          type: 1,
          uf: 1,
          reason: 1,
          notes: 1,
          date: 1,
          email: 1
        }
      },
      {
        '$group': {
          _id: { day: '$day', uf: '$uf' },
          cases: { '$push': '$$ROOT' }
        }
      },
      {
        '$sort': { '_id.day': -1, '_id.uf': 1 }
      }
    ]).map do |day_uf|
      RecursiveOpenStruct.new day_uf, recurse_over_arrays: true
    end
  end

  TYPES = {
    phone: 'Telefone',
    chat: 'Chat',
    email: 'Email',
  }

  BRAZIL_UFS = {
    AC: 'Acre',
    AL: 'Alagoas',
    AM: 'Amazonas',
    AP: 'Amapá',
    BA: 'Bahia',
    CE: 'Ceará',
    DF: 'Distrito Federal',
    ES: 'Espírito Santo',
    GO: 'Goiás',
    MA: 'Maranhão',
    MG: 'Minas Gerais',
    MS: 'Mato Grosso do Sul',
    MT: 'Mato Grosso',
    PA: 'Pará',
    PB: 'Paraíba',
    PE: 'Pernambuco',
    PI: 'Piauí',
    PR: 'Paraná',
    RJ: 'Rio de Janeiro',
    RN: 'Rio Grande do Norte',
    RO: 'Rondônia',
    RR: 'Roraima',
    RS: 'Rio Grande do Sul',
    SC: 'Santa Catarina',
    SE: 'Sergipe',
    SP: 'São Paulo',
    TO: 'Tocantins',    
  }

  REASONS = {
    question: 'Dúvida',
    compliment: 'Elogio',
    suggestion: 'Sugestão',
  }

  field :type
  field :uf
  field :reason
  field :notes
  field :date, type: DateTime
  field :email

  before_create :save_date

  validates :type, presence: true, inclusion: TYPES.keys.map {|key| key.to_s}
  validates :uf, presence: true, inclusion: BRAZIL_UFS.keys.map {|key| key.to_s}
  validates :reason, presence: true, inclusion: REASONS.keys.map {|key| key.to_s}
  validates :notes, presence: true
  validates :email, presence: true

protected

  def save_date
    self.date ||= DateTime.now
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  index({ email: 1 }, { unique: true })

  validates :email, uniqueness: true

  def will_save_change_to_email?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  before_action :authenticate_user!

  def index
    redirect_to :new_case
  end

  def show
    @case = Case.find params[:id]
  end

  def new
    @case = Case.new
  end

  def create
    @case = Case.new case_params
    @case.email = current_user.email
    if @case.save
      redirect_to @case
    else
      render 'new'
    end
  end

private

  def case_params
    params.require(:case).permit :type, :uf, :reason, :notes
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_admin!

  def show
    @report = Case.report    
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
    if admin_signed_in?
      redirect_to :report
    elsif user_signed_in?
      redirect_to :cases
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

private

  def user_params
    params.require(:user).permit :email, :password
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cases/new.html.erb
<h2>Novo atendimento</h2>
<% if @case.errors.any? %>
  <ul>
    <% @case.errors.full_messages.each do |full_message| %>
      <li><%= full_message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for :case, url: cases_path do |f| %>
  <p>
    <%= f.label 'Tipo' %><br>
    <% Case::TYPES.each do |key, value| %>
      <%= f.radio_button :type, key %>
      <%= f.label :type, value, value: key %>
    <% end %>
  </p>
  <p>
    <%= f.label 'UF' %><br>
    <%= f.select :uf, Case::BRAZIL_UFS.invert, prompt: 'Escolha...' %>
  </p>
  <p>
    <%= f.label 'Motivo' %><br>
    <% Case::REASONS.each do |key, value| %>
      <%= f.radio_button :reason, key %>
      <%= f.label :reason, value, value: key %>
    <% end %>
  </p>
  <p>
    <%= f.label 'Anotações' %><br>
    <%= f.text_area :notes %>
  </p>
  <p>
    <%= f.submit 'Encerrar atendimento' %>
  </p>
<% end %>
<hr/>
<%= link_to 'Sair', destroy_user_session_path, method: :delete %>

app/views/cases/show.html.erb
<h2>Atendimento encerrado</h2>
<strong>Horário:</strong> <span id='date'><%= @case.date %></span><br/>
<strong>Tipo:</strong> <span id='type'><%= Case::TYPES[@case.type.to_sym] %></span><br/>
<strong>UF:</strong> <span id='uf'><%= Case::BRAZIL_UFS[@case.uf.to_sym] %></span><br/>
<strong>Motivo:</strong> <span id='reason'><%= Case::REASONS[@case.reason.to_sym] %></span><br/>
<strong>Anotações:</strong><br/><textarea readonly><%= @case.notes %></textarea><br/>
<strong>Atendente:</strong> <span id='email'><%= @case.email %></span><br/>
<hr/>
<%= link_to 'Iniciar novo atendimento', new_case_path %>
<span> | </span>
<%= link_to 'Sair', destroy_user_session_path, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cszero</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/reports/show.html.erb
<% if @report.present? %>
  <table>
    <thead>
      <tr>
        <th>Dia</th>
        <th>UF</th>
        <th>Hora</th>
        <th>Tipo</th>
        <th>Motivo</th>
        <th>Anotações</th>
        <th>Atendente</th>
      </tr>
    </thead>
    <tbody>
    <% @report.each do |day_uf| %>
      <tr>
        <td rowspan="<%= day_uf.cases.length %>"><%= day_uf._id.day %></td>
        <td rowspan="<%= day_uf.cases.length %>"><%= Case::BRAZIL_UFS[day_uf._id.uf.to_sym] %></td>
        <% day_uf.cases.each do |individual_case| %>
          <td><%= individual_case.date.strftime '%H:%M:%S%z' %></td>
          <td><%= Case::TYPES[individual_case.type.to_sym] %></td>
          <td><%= Case::REASONS[individual_case.reason.to_sym] %></td>
          <td><%= individual_case.notes %></td>
          <td><%= individual_case.email %></td>
          </tr>
          <tr>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>
<hr/>
<%= link_to 'Criar novo atendente', new_user_path %>
<span> | </span>
<%= link_to 'Sair', destroy_admin_session_path, method: :delete %>

app/views/root/index.html.erb
<%= link_to 'Acesso atendente', new_user_session_path %>
<span> | </span>
<%= link_to 'Acesso admin', new_admin_session_path %>

app/views/users/index.html.erb
<% if @report.present? %>
  <table>
    <thead>
      <tr>
        <th>Dia</th>
        <th>UF</th>
        <th>Hora</th>
        <th>Tipo</th>
        <th>Motivo</th>
        <th>Anotações</th>
        <th>Atendente</th>
      </tr>
    </thead>
    <tbody>
    <% @report.each do |day_uf| %>
      <tr>
        <td rowspan="<%= day_uf.cases.length %>"><%= day_uf._id.day %></td>
        <td rowspan="<%= day_uf.cases.length %>"><%= Case::BRAZIL_UFS[day_uf._id.uf.to_sym] %></td>
        <% day_uf.cases.each do |individual_case| %>
          <td><%= individual_case.date.strftime '%H:%M:%S%z' %></td>
          <td><%= Case::TYPES[individual_case.type.to_sym] %></td>
          <td><%= Case::REASONS[individual_case.reason.to_sym] %></td>
          <td><%= individual_case.notes %></td>
          <td><%= individual_case.email %></td>
          </tr>
          <tr>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>
<hr/>
<%= link_to 'Criar novo atendente', new_user_path %>
<span> | </span>
<%= link_to 'Sair', destroy_admin_session_path, method: :delete %>

app/views/users/new.html.erb
<h2>Novo atendente</h2>
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |full_message| %>
      <li><%= full_message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for :user, url: users_path do |f| %>
  <p>
    <%= f.label 'email' %><br>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label 'senha' %><br>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.submit 'Criar' %>
  </p>
<% end %>
<hr/>
<%= link_to 'Sair', destroy_admin_session_path, method: :delete %>

app/views/users/show.html.erb
<h2>Atendente criado</h2>
<strong>Email:</strong> <span id='email'><%= @user.email %></span>
<hr/>
<%= link_to 'Criar novo atendente', new_user_path %>
<span> | </span>
<%= link_to 'Relatório', report_path %>
<span> | </span>
<%= link_to 'Sair', destroy_admin_session_path, method: :delete %>